### ISSUE TITLE
wordpress-centos7-atomicapp errors out on fedora atomic 22

### ISSUE THREAD

**Issue by jasonbrooks** [projectatomic/nulecule#141]
On fedora-atomic 22.87 (`kubernetes-1.0.0-0.9.git2d88675` & `docker-1.7.1-4.gitcc60fc3` ), running `sudo atomic run projectatomic/wordpress-centos7-atomicapp` errors out:

```
2015-08-06 21:21:35,844 - atomicapp.install - DEBUG - ['docker', 'cp', 'wordpress-centos7-atomicapp-TcVrjq:/application-entity', '/tmp/nulecule-kUdMCL']
FATA[0000] Error response from daemon: Could not find the file /application-entity in container wordpress-centos7-atomicapp-TcVrjq 
wordpress-centos7-atomicapp-TcVrjq
2015-08-06 21:21:36,040 - atomicapp.install - DEBUG - Nulecule path for pulled image: /tmp/nulecule-kUdMCL/application-entity/Nulecule
Traceback (most recent call last):
  File "/usr/bin/atomicapp", line 9, in <module>
    load_entry_point('atomicapp==0.1', 'console_scripts', 'atomicapp')()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 89, in main
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 70, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomicapp/cli/main.py", line 20, in cli_run
    ae = Run(**vars(args))
  File "/usr/lib/python2.7/site-packages/atomicapp/run.py", line 64, in __init__
    install.install()
  File "/usr/lib/python2.7/site-packages/atomicapp/install.py", line 98, in install
    self.nulecule_base.loadMainfile(mainfile_path)
  File "/usr/lib/python2.7/site-packages/atomicapp/nulecule_base.py", line 88, in loadMainfile
    raise Exception("%s not found: %s" % (MAIN_FILE, path))
Exception: Nulecule not found: /tmp/nulecule-kUdMCL/application-entity/Nulecule
```

**Comment by goern** [comment]
will track it here, as atomicapp seems to be broken, https://github.com/projectatomic/atomicapp/issues/194 is blocking the rebuild of working examples, hub.docker.com needs to be updated too.

**Comment by dustymabe** [comment]
@goern @jasonbrooks I think this can be closed now

**Comment by goern** [comment]
@dustymabe thats a 'I have rerun the test and it work' ? ;)

**Comment by dustymabe** [comment]
@goern That is a 'I have rerun test and got farther than this'. So I think we can close this. See https://github.com/projectatomic/nulecule/issues/162 for the new issue that I am seeing.

**Comment by goern** [comment]
Thanks Dusty!
